name: Code Review Bot

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm init -y && npm install axios

      - name: Run Review Script
        run: node .github/agents/code review.agent.md
        env:
          GITHUB_TOKEN: ${{ secrets.SELPWSECRET}}
